RUN_STRINGS = (
    "Di mana Anda pikir Anda akan pergi?",
    "Hah? apa? mereka kabur?",
    "ZZzzZZzz... Hah? apa? oh, hanya mereka lagi, sudahlah.",
    "Kembali kesini!",
    "Tidak secepat itu...",
    "Awas tembok!",
    "Jangan tinggalkan aku sendiri dengan mereka!!",
    "Kamu lari, kamu mati.",
    "Bercanda denganmu, aku ada di mana-mana",
    "Kau akan menyesalinya...",
    "Anda juga bisa mencoba /kickme, saya dengar itu menyenangkan.",
    "Pergi ganggu orang lain, tidak ada yang peduli di sini.",
    "Kamu bisa lari, tapi kamu tidak bisa bersembunyi.",
    "Hanya itu yang kamu punya?",
    "Saya di belakang Anda...",
    "Kamu punya teman!",
    "Kita bisa melakukan ini dengan cara yang mudah, atau dengan cara yang sulit.",
    "Kamu hanya tidak mengerti, kan?",
    "Ya, lebih baik kamu lari!",
    "Tolong, ingatkan aku betapa aku peduli?",
    "Aku akan berlari lebih cepat jika aku jadi kamu.",
    "Itu pasti droid yang kita cari.",
    "Semoga peluang selalu menguntungkan Anda.",
    "Kata-kata terakhir yang terkenal.",
    "Dan mereka menghilang selamanya, tidak pernah terlihat lagi.",
    '"Oh, lihat aku! Aku sangat keren, aku bisa lari dari bot!" - orang ini',
    "Ya ya, ketuk saja / tendang aku.",
    "Ini, ambil cincin ini dan pergilah ke Mordor selagi kau melakukannya.",
    "Legenda mengatakannya, mereka masih berjalan...",
    "Tidak seperti Harry Potter, orang tuamu tidak bisa melindungimu dariku.",
    "Ketakutan menimbulkan kemarahan. Kemarahan menimbulkan kebencian. Kebencian menimbulkan penderitaan. Jika Anda terus berlari dalam ketakutan, Anda mungkin"
    "jadilah Vader berikutnya.",
    "Berbagai perhitungan kemudian, saya telah memutuskan minat saya pada kejahatan Anda tepat 0.",
    "Legenda memilikinya, mereka masih berjalan.",
    "Teruskan, tidak yakin kami tetap menginginkanmu di sini.",
    "Kamu seorang wiza- Oh. Tunggu. Kamu bukan Harry, teruslah bergerak.",
    "DILARANG BERLARI DI LUBANG!",
    "Hasta la vista, sayang.",
    "Siapa yang membiarkan anjing-anjing itu keluar?",
    "Lucu, karena tidak ada yang peduli.",
    "Ah, sayang sekali. Aku suka yang itu.",
    "Terus terang, sayangku, aku tidak peduli.",
    "Milkshake saya membawa semua anak laki-laki ke halaman... Jadi larilah lebih cepat!",
    "Kamu tidak bisa MENANGANI kebenaran!",
    "Dahulu kala, di galaksi yang sangat jauh... Seseorang akan peduli tentang itu. Tapi sekarang tidak lagi.",
    "Hei, lihat mereka! Mereka lari dari banhammer yang tak terelakkan... Lucu.",
    "Han menembak lebih dulu. Aku juga.",
    "Apa yang kamu kejar, kelinci putih?",
    "Seperti yang dikatakan Dokter... LARI!",
)

SLAP_Kigyō_TEMPLATES = (
    "Tampar aku sekali lagi dan aku akan membisukanmu.",
    "Berhentilah menamparku. REEEEEEEEEEEEEE.",
    [
        "Saya membisukan Anda sebentar.", # Balasan normal
        "Berhentilah menamparku hanya karena aku tidak bisa membisukanmu. REEEEEEEEEE.", # balas admin
        "matikan",  # command
    ],
)

SLAP_TEMPLATES = (
    "{user2} ditembak oleh {user1}.",
    "{user2} masuk ke kaktus sambil mencoba melarikan diri {user1}.",
    "{user2} tenggelam saat mencoba melarikan diri {user1}.",
    "{user2} jatuh ke sepetak kaktus.",
    "{user2} terbakar.",
    "{user2} terbakar sampai mati.",
    "{user2} dibakar habis saat bertarung dengan {user1}.",
    "{user2} tersambar petir.",
    "{user2} dibunuh oleh {user1}.",
    "{user2} dibunuh oleh sihir.",
    "{user2} mati kelaparan.",
    "{user2} jatuh dari dunia.",
    "{user2} dijatuhkan ke dalam kekosongan oleh {user1}.",
    "Tulang {pengguna2} tergores bersih oleh angin sunyi.",
    "{user2} pingsan.",
    "{user2} kehabisan Pokemon yang bisa digunakan! {user2} mati total!.",
    "{user2} kehabisan Pokemon yang bisa digunakan! {user2} pingsan!.",
    "{user2} mengucapkan selamat tinggal pada dunia yang kejam ini.",
    "{user2} punya rekt.",
    "{user2} digergaji menjadi dua oleh {user1}.",
    "Melon {user2} dibagi oleh {user1}.",
    "{user2} diiris dan dipotong dadu oleh {user1}.",
    "Kematian {pengguna2} menempatkan kedudukan lain di kapak {pengguna1}.",
    "{user2} meninggal karena penyakit tropis misterius {user1}.",
    "{user2} bermain hot-potato dengan granat.",
    "{user2} ditikam oleh {user1}.",
    "{user2} makan granat.",
    "{user2} apa untuk makan malam!",
    "{user2} telah dihentikan oleh {user1}.",
    "{user2} ditembak sebelum dilempar keluar dari pesawat.",
    "{user2} mengalami kesalahan.",
    "{user2} mati dan bereinkarnasi sebagai kambing.",
    "{user1} melempar {user2} dari gedung.",
    "{user2} mendapat penguburan prematur.",
    "{user1} mengirim spam ke email {user2}.",
    "{user1} menabrak {user2} dengan pesawat luar angkasa kecil antarbintang.",
    "{user1} tempatkan {user2} di skakmat.",
    "{user1} mengenkripsi RSA {user2} dan menghapus kunci pribadi.",
    "{user1} tempatkan {user2} di zona pertemanan.",
    "{user1} menampar {user2} dengan permintaan penghapusan DMCA!",
    "{user2} meninggal karena gangren rumah sakit.",
    "{user2} mendapat telepon rumah dari Dokter {user1}.",
    "{user1} memenggal {user2}.",
    "{user2} dilempari batu...oleh massa yang marah.",
    "{user1} menggugat celana {user2}.",
    "{user2} adalah KO satu pukulan oleh {user1}.",
    "{user1} mengirim {user2} ke lubang memori.",
    "{user2} adalah kesalahan. - '{user1}'",
    "{user1} melakukan skakmat {user2} dalam dua gerakan.",
    "{user2} dibuat mubazir.",
    "{user1} {memukul} {user2} dengan kelelawar!.",
    "{user1} {hits} {user2} dengan Jurus Taijutsu!.",
    "{user1} {hits} {user2} dengan X-Gloves!.",
    "{user1} {hits} {user2} dengan Jet Punch!.",
    "{user1} {hits} {user2} dengan Jet Pistol!.",
    "{user1} {hits} {user2} dengan United States of Smash!.",
    "{user1} {hits} {user2} dengan Detroit Smash!.",
    "{user1} {hits} {user2} dengan Texas Smash!.",
    "{user1} {hits} {user2} dengan California Smash!.",
    "{user1} {hits} {user2} dengan New Hampshire Smash!.",
    "{user1} {hits} {user2} dengan Missouri Smash!.",
    "{user1} {hits} {user2} dengan Carolina Smash!.",
    "{user1} {hits} {user2} dengan King Kong Gun!.",
    "{user1} {memukul} {user2} dengan tongkat bisbol - logam.!.",
    "* Pukulan serius {user2}*.",
    "* Pukulan biasa {user2}*.",
    "* Pukulan normal berturut-turut {user2}*.",
    "* Pukulan Normal Dua Tangan Berturut-turut {user2}*.",
    "*Abaikan {user2} untuk membiarkan mereka mati karena malu*.",
    "*menunjuk {user2}* Ada apa dengan lancang... anak hilang ini?.",
    "*Pukul {user2} dengan Fire Tornado*.",
    "{user1} menusuk mata {user2}!",
    "{user1} menyodok {user2} di samping!",
    "{user1} colek {user2}!",
    "{user1} menusuk {user2} dengan jarum!",
    "{user1} menusuk {user2} dengan pena!",
    "{user1} menusuk {user2} dengan senjata bius!",
    "{user2} diam-diam adalah Furry!.",
    "Hai Semuanya! {user1} meminta saya untuk menjadi jahat!",
    "( ･_･)ﾉ⌒●~* (･.･;) <-{pengguna2}",
    "Ambil ini {pengguna2}\n(ﾉﾟДﾟ)ﾉ ))))●~* ",
    "Ini {pengguna2} pegang ini\n(｀・ω・)つ ●~＊",
    "( ・_・)ノΞ●~* {pengguna2}, Shineeeeee!!.",
    "( ・∀・)ｒ鹵~<≪巛;ﾟДﾟ)ﾉ\n*Bug menyemprot {user2}*.",
    "( ﾟДﾟ)ﾉ占~<巛巛巛.\n-{pengguna2} Kamu menyebalkan!",
    "( う-´)づ︻╦̵̵̿╤── \(˚☐˚”)/ {pengguna2}.",
    "{user1} {memukul} {user2} dengan {item}.",
    "{user1} {hits} {user2} di muka dengan {item}.",
    "{user1} {hits} {user2} sedikit dengan {item}.",
    "{user1} {melempar} {item} ke {user2}.",
    "{user1} mengambil {item} dan {melemparnya} ke wajah {user2}.",
    "{user1} meluncurkan {item} ke arah umum {user2}.",
    "{user1} mulai menampar {user2} konyol dengan {item}.",
    "{user1} menyematkan {user2} ke bawah dan berulang kali {memukul} mereka dengan {item}.",
    "{user1} mengambil {item} dan {hits} {user2} dengan itu.",
    "{user1} mengikat {user2} ke kursi dan {melempar} {item} ke arah mereka.",
    "{user1} memberikan dorongan ramah untuk membantu {user2} belajar berenang di lahar.",
    "{user1} menindas {user2}.",
    "Nyaan memakan kaki {user2}. *nomnomnom*",
    "{user1} {melempar} bola master ke {user2}, perlawanan sia-sia.",
    "{user1} mengenai {user2} dengan action beam...bbbbbb (ง・ω・)ง ====*",
    "{user1} ara ara {user2}.",
    "{user1} ora ora {user2}.",
    "{user1} muda muda {user2}.",
    "{user2} diubah menjadi referensi Jojo!",
    "{user1} memukul {user2} dengan {item}.",
    "Ronde 2!..Siap?.. FIGHT!!",
)

PING_STRING = (
    "PONG!!",
    "Saya disini!",
)

ITEMS = (
    "wajan besi cor",
    "meong marah",
    "pemukul kriket",
    "tongkat kayu",
    "sekop",
    "pemanggang roti",
    "buku",
    "laptop",
    "ayam karet",
    "kelelawar berduri",
    "batu berat",
    "kotoran",
    "ton batu bata",
    "rasengan",
    "bom roh",
    "Bodhisattva Guanyin Tipe 100",
    "rasenshuriken",
    "Murasame",
    "melarang",
    "chunchunmaru",
    "Kubikiribōchō",
    "rasengan",
    "kat terbang bulat",
)

LEMBAR = (
    "melempar",
    "teman kencan",
    "chuck",
    "melemparkan",
)

TEKAN = (
    "hit",
    "pukulan",
    "tamparan",
    "memukul",
    "pesta",
    "tepukan",
)

EYES = [
    ["⌐■", "■"],
    [" ͠°", " °"],
    ["⇀", "↼"],
    ["´• ", " •`"],
    ["´", "`"],
    ["`", "´"],
    ["ó", "ò"],
    ["ò", "ó"],
    ["⸌", "⸍"],
    [">", "<"],
    ["Ƹ̵̡", "Ʒ"],
    ["ᗒ", "ᗕ"],
    ["⟃", "⟄"],
    ["⪧", "⪦"],
    ["⪦", "⪧"],
    ["⪩", "⪨"],
    ["⪨", "⪩"],
    ["⪰", "⪯"],
    ["⫑", "⫒"],
    ["⨴", "⨵"],
    ["⩿", "⪀"],
    ["⩾", "⩽"],
    ["⩺", "⩹"],
    ["⩹", "⩺"],
    ["◥▶", "◀◤"],
    ["◍", "◎"],
    ["/͠-", "┐͡-\\"],
    ["⌣", "⌣”"],
    [" ͡⎚", " ͡⎚"],
    ["≋"],
    ["૦ઁ"],
    ["  ͯ"],
    ["  ͌"],
    ["ළ"],
    ["◉"],
    ["☉"],
    ["・"],
    ["▰"],
    ["ᵔ"],
    [" ﾟ"],
    ["□"],
    ["☼"],
    ["*"],
    ["`"],
    ["⚆"],
    ["⊜"],
    [">"],
    ["❍"],
    ["￣"],
    ["─"],
    ["✿"],
    ["•"],
    ["T"],
    ["^"],
    ["ⱺ"],
    ["@"],
    ["ȍ"],
    ["  "],
    ["  "],
    ["x"],
    ["-"],
    ["$"],
    ["Ȍ"],
    ["ʘ"],
    ["Ꝋ"],
    [""],
    ["⸟"],
    ["๏"],
    ["ⴲ"],
    ["◕"],
    ["◔"],
    ["✧"],
    ["■"],
    ["♥"],
    [" ͡°"],
    ["¬"],
    [" º "],
    ["⨶"],
    ["⨱"],
    ["⏓"],
    ["⏒"],
    ["⍜"],
    ["⍤"],
    ["ᚖ"],
    ["ᴗ"],
    ["ಠ"],
    ["σ"],
    ["☯"],
]

MOUTHS = [
    ["v"],
    ["ᴥ"],
    ["ᗝ"],
    ["Ѡ"],
    ["ᗜ"],
    ["Ꮂ"],
    ["ᨓ"],
    ["ᨎ"],
    ["ヮ"],
    ["╭͜ʖ╮"],
    [" ͟ل͜"],
    [" ͜ʖ"],
    [" ͟ʖ"],
    [" ʖ̯"],
    ["ω"],
    [" ³"],
    [" ε "],
    ["﹏"],
    ["□"],
    ["ل͜"],
    ["‿"],
    ["╭╮"],
    ["‿‿"],
    ["▾"],
    ["‸"],
    ["Д"],
    ["∀"],
    ["!"],
    ["人"],
    ["."],
    ["ロ"],
    ["_"],
    ["෴"],
    ["ѽ"],
    ["ഌ"],
    ["⏠"],
    ["⏏"],
    ["⍊"],
    ["⍘"],
    ["ツ"],
    ["益"],
    ["╭∩╮"],
    ["Ĺ̯"],
    ["◡"],
    [" ͜つ"],
]

EARS = [
    ["q", "p"],
    ["ʢ", "ʡ"],
    ["⸮", "?"],
    ["ʕ", "ʔ"],
    ["ᖗ", "ᖘ"],
    ["ᕦ", "ᕥ"],
    ["ᕦ(", ")ᕥ"],
    ["ᕙ(", ")ᕗ"],
    ["ᘳ", "ᘰ"],
    ["ᕮ", "ᕭ"],
    ["ᕳ", "ᕲ"],
    ["(", ")"],
    ["[", "]"],
    ["¯\\_", "_/¯"],
    ["୧", "୨"],
    ["୨", "୧"],
    ["⤜(", ")⤏"],
    ["☞", "☞"],
    ["ᑫ", "ᑷ"],
    ["ᑴ", "ᑷ"],
    ["ヽ(", ")ﾉ"],
    ["\\(", ")/"],
    ["乁(", ")ㄏ"],
    ["└[", "]┘"],
    ["(づ", ")づ"],
    ["(ง", ")ง"],
    ["⎝", "⎠"],
    ["ლ(", "ლ)"],
    ["ᕕ(", ")ᕗ"],
    ["(∩", ")⊃━☆ﾟ.*"],
]

TOS = (
    "Kepala",
    "Ekor",
)

MEMUTUSKAN = ("Ya.", "Tidak.", "Mungkin.")

TABEL = (
    "(╯°□°）╯彡 ┻━┻",
    "Saya kehabisan meja, akan memesan lebih banyak.",
    "Lakukan beberapa pekerjaan alih-alih meja flippin.",
)
